# Generated by Django 4.2.12 on 2025-01-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sale_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='last_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='last_activity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
