# Generated by Django 4.2.12 on 2025-01-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_items_last_activity_items_last_activity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='items',
            name='last_activity_date',
        ),
    ]
